spring:
  datasource:
    # по умолчанию — локальный Postgres, если не заданы переменные окружения
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${SPRING_DATASOURCE_USERNAME:library}
    password: ${SPRING_DATASOURCE_PASSWORD:library}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    # ВАЖНО: сначала Hibernate создаёт таблицы, потом выполняется data.sql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8080

